// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Manufacturer is the predicate function for manufacturer builders.
type Manufacturer func(*sql.Selector)

// Product is the predicate function for product builders.
type Product func(*sql.Selector)

// Review is the predicate function for review builders.
type Review func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
