// Code generated by entc, DO NOT EDIT.

package manufacturer

import (
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the manufacturer type in the database.
	Label = "manufacturer"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// Table holds the table name of the manufacturer in the database.
	Table = "manufacturers"
)

// Columns holds all SQL columns for manufacturer fields.
var Columns = []string{
	FieldID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)
