// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Manufacturer struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (Manufacturer) IsEntity() {}

type NewManufaturer struct {
	Name string `json:"name"`
}

type Product struct {
	ID           string        `json:"id"`
	Upc          string        `json:"upc"`
	Name         string        `json:"name"`
	Price        int           `json:"price"`
	Manufacturer *Manufacturer `json:"manufacturer"`
}

func (Product) IsEntity() {}
