// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewManufaturer struct {
	Name string `json:"name"`
}

type NewProduct struct {
	Name  string `json:"name"`
	Upc   string `json:"upc"`
	Price int    `json:"price"`
}
