// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/google/uuid"
	"github.com/johannmunoz/gql_postgres_go/cmd/reviews/ent/manufacturer"
)

// Manufacturer is the model entity for the Manufacturer schema.
type Manufacturer struct {
	config
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Manufacturer) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case manufacturer.FieldID:
			values[i] = new(uuid.UUID)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Manufacturer", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Manufacturer fields.
func (m *Manufacturer) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case manufacturer.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				m.ID = *value
			}
		}
	}
	return nil
}

// Update returns a builder for updating this Manufacturer.
// Note that you need to call Manufacturer.Unwrap() before calling this method if this Manufacturer
// was returned from a transaction, and the transaction was committed or rolled back.
func (m *Manufacturer) Update() *ManufacturerUpdateOne {
	return (&ManufacturerClient{config: m.config}).UpdateOne(m)
}

// Unwrap unwraps the Manufacturer entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (m *Manufacturer) Unwrap() *Manufacturer {
	tx, ok := m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Manufacturer is not a transactional entity")
	}
	m.config.driver = tx.drv
	return m
}

// String implements the fmt.Stringer.
func (m *Manufacturer) String() string {
	var builder strings.Builder
	builder.WriteString("Manufacturer(")
	builder.WriteString(fmt.Sprintf("id=%v", m.ID))
	builder.WriteByte(')')
	return builder.String()
}

// Manufacturers is a parsable slice of Manufacturer.
type Manufacturers []*Manufacturer

func (m Manufacturers) config(cfg config) {
	for _i := range m {
		m[_i].config = cfg
	}
}

func (Manufacturer) IsEntity() {}
